export const formattedInvoices = [
    {
        due_date: "2021-08-19",
        client_name: "Jensen Huang",
        client_email: "jensenh@mail.com",
        street_from: "19 Union Terrace",
        street_to: "106 Kendell Street",
        city_from: "London",
        city_to: "Sharrington",
        postcode_from: "E1 3EZ",
        postcode_to: "NR24 5WQ",
        country_from: "United Kingdom",
        country_to: "United Kingdom",
        invoice_date: "2021-08-18",
        status: "PAID",
        payment_terms: "ONE",
        description: "Re-branding",
        total: 1800.9,
        items: [
            {
                name: "Brand Guidelines",
                quantity: 1,
                price: 1800.9,
                total: 1800.9,
            },
        ],
    },
    {
        due_date: "2021-09-20",
        client_name: "Alex Grim",
        client_email: "alexgrim@mail.com",
        street_from: "19 Union Terrace",
        street_to: "84 Church Way",
        city_from: "London",
        city_to: "Bradford",
        postcode_from: "E1 3EZ",
        postcode_to: "BD1 9PB",
        country_from: "United Kingdom",
        country_to: "United Kingdom",
        invoice_date: "2021-08-21",
        status: "PENDING",
        payment_terms: "THIRTY",
        description: "Graphic Design",
        total: 556.0,
        items: [
            {
                name: "Banner Design",
                quantity: 1,
                price: 156.0,
                total: 156.0,
            },
            {
                name: "Email Design",
                quantity: 2,
                price: 200.0,
                total: 400.0,
            },
        ],
    },
    {
        due_date: "2021-10-01",
        client_name: "John Morrison",
        client_email: "jm@myco.com",
        street_from: "19 Union Terrace",
        street_to: "79 Dover Road",
        city_from: "London",
        city_to: "Westhall",
        postcode_from: "E1 3EZ",
        postcode_to: "IP19 3PF",
        country_from: "United Kingdom",
        country_to: "United Kingdom",
        invoice_date: "2021-09-24",
        status: "PAID",
        payment_terms: "SEVEN",
        description: "Website Redesign",
        total: 14002.33,
        items: [
            {
                name: "Website Redesign",
                quantity: 1,
                price: 14002.33,
                total: 14002.33,
            },
        ],
    },
    {
        due_date: "2021-10-12",
        client_name: "Alysa Werner",
        client_email: "alysa@email.co.uk",
        street_from: "19 Union Terrace",
        street_to: "63 Warwick Road",
        city_from: "London",
        city_to: "Carlisle",
        postcode_from: "E1 3EZ",
        postcode_to: "CA20 2TG",
        country_from: "United Kingdom",
        country_to: "United Kingdom",
        invoice_date: "2021-10-11",
        status: "PENDING",
        payment_terms: "ONE",
        description: "Logo Concept",
        total: 102.04,
        items: [
            {
                name: "Logo Sketches",
                quantity: 1,
                price: 102.04,
                total: 102.04,
            },
        ],
    },
    {
        due_date: "2021-10-14",
        client_name: "Mellisa Clarke",
        client_email: "mellisa.clarke@example.com",
        street_from: "19 Union Terrace",
        street_to: "46 Abbey Row",
        city_from: "London",
        city_to: "Cambridge",
        postcode_from: "E1 3EZ",
        postcode_to: "CB5 6EG",
        country_from: "United Kingdom",
        country_to: "United Kingdom",
        invoice_date: "2021-10-07",
        status: "PENDING",
        payment_terms: "SEVEN",
        description: "Re-branding",
        total: 4032.33,
        items: [
            {
                name: "New Logo",
                quantity: 1,
                price: 1532.33,
                total: 1532.33,
            },
            {
                name: "Brand Guidelines",
                quantity: 1,
                price: 2500.0,
                total: 2500.0,
            },
        ],
    },
    {
        due_date: "2021-10-31",
        client_name: "Thomas Wayne",
        client_email: "thomas@dc.com",
        street_from: "19 Union Terrace",
        street_to: "3964  Queens Lane",
        city_from: "London",
        city_to: "Gotham",
        postcode_from: "E1 3EZ",
        postcode_to: "60457",
        country_from: "United Kingdom",
        country_to: "United States of America",
        invoice_date: "2021-10-01",
        status: "PENDING",
        payment_terms: "THIRTY",
        description: "Landing Page Design",
        total: 6155.91,
        items: [
            {
                name: "Web Design",
                quantity: 1,
                price: 6155.91,
                total: 6155.91,
            },
        ],
    },
    {
        due_date: "2021-11-12",
        client_name: "Anita Wainwright",
        client_email: "",
        street_from: "19 Union Terrace",
        street_to: "",
        city_from: "London",
        city_to: "",
        postcode_from: "E1 3EZ",
        postcode_to: "",
        country_from: "United Kingdom",
        country_to: "",
        invoice_date: "2021-11-05",
        status: "DRAFT",
        payment_terms: "SEVEN",
        description: "Logo Re-design",
        total: 3102.04,
        items: [
            {
                name: "Logo Re-design",
                quantity: 1,
                price: 3102.04,
                total: 3102.04,
            },
        ],
    },
];
